# Entrenamiento YOLO con parches imagenes originales 640

Objetivo: entrenar YOLOv11n con el dataset de parches generado en el notebook anterior para mejorar la detección de kanjis respecto a las pruebas con imágenes completas.

In [ ]:
from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model.train(
    data="/home/salvarado/TFM/Dataset_preparados/dataset_kanji_parches/originales/dataset_parches_originales.yaml",
    epochs=50,
    imgsz=640,
    batch=8,
    patience=10,
    device=0,
    project="/home/salvarado/TFM/resultados/result_yolo",
    name="parches_originales_640_50ep",
    seed=42
)

Ultralytics 8.4.61 🚀 Python-3.11.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11163MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/salvarado/TFM/Dataset_preparados/dataset_kanji_parches/originales/dataset_parches_originales.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=parches_origina

## Entrenamiento con parches denoised 640

Se repite el entrenamiento con el dataset de parches denoised para comparar con los resultados de original.

In [1]:
from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model.train(
    data="/home/salvarado/TFM/Dataset_preparados/dataset_kanji_parches/denoised/dataset_parches_denoised.yaml",
    epochs=50,
    imgsz=640,
    batch=8,
    patience=10,
    device=0,
    project="/home/salvarado/TFM/resultados/result_yolo",
    name="parches_denoised_640_50ep",
    seed=42
)

Ultralytics 8.4.61 🚀 Python-3.11.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11163MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/salvarado/TFM/Dataset_preparados/dataset_kanji_parches/denoised/dataset_parches_denoised.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=parches_denoised_64

## Análisis

Con parches, original y denoised obtienen resultados casi parecidos esto tiene sentido: cuando los kanjis se ven grandes y claros dentro del parche, el ruido de fondo ya no es un problema para el modelo, En cambio, con imágenes completas el denoised sí ayudaba porque el modelo tenía dificultades para distinguir los kanjis del ruido al verlos tan pequeños.

Lo más importante es que ambos modelos superan mAP50=0.96, frente al 0.717 que era el mejor resultado con imágenes completas. Esto confirma que dividir en parches es la solución clave para este problema.

## Entrenamiento con parches imgsz originales 1024

Se prueba entrenar con imgsz=1024 sobre los parches para comprobar si mejora respecto a imgsz=640. Si los resultados son similares, confirma que 640 es la configuración óptima.


In [1]:
from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model.train(
    data="/home/salvarado/TFM/Dataset_preparados/dataset_kanji_parches/originales/dataset_parches_originales.yaml",
    epochs=50,
    imgsz=1024,
    batch=4,
    patience=10,
    device=0,
    project="/home/salvarado/TFM/resultados/result_yolo",
    name="parches_originales_1024_50ep",
    seed=42
)

Ultralytics 8.4.61 🚀 Python-3.11.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11163MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/salvarado/TFM/Dataset_preparados/dataset_kanji_parches/originales/dataset_parches_originales.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=1024, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=parches_origin

## Análisis

El modelo con imgsz=1024 mejora ligeramente respecto al de 640 en todas las métricas, especialmente en recall (0.931 → 0.945) esto indica que con un tamaño de imagen mayor los kanjis se ven con más detalle dentro del parche, facilitando su detección. sin embargo la diferencia es pequeña, lo que confirma que imgsz=640 ya era una buena configuración para este dataset. Se usará el modelo de 1024 como definitivo por tener el mejor recall.

133 × (1024 / 2048) ≈ 66 px
Con imgsz=640 ya quedaban a 41px y los resultados eran buenos (mAP50=0.971). Con 1024 los kanjis se ven aún más grandes (66px), lo que mejora ligeramente el recall.


## Entrenamiento con parches denoised imgsz=1024

Se repite el experimento con imgsz=1024 para el dataset denoised para comparar con los resultados de original.

In [2]:
from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model.train(
    data="/home/salvarado/TFM/Dataset_preparados/dataset_kanji_parches/denoised/dataset_parches_denoised.yaml",
    epochs=50,
    imgsz=1024,
    batch=4,
    patience=10,
    device=0,
    project="/home/salvarado/TFM/resultados/result_yolo",
    name="parches_denoised_1024_50ep",
    seed=42
)

Ultralytics 8.4.61 🚀 Python-3.11.15 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11163MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/salvarado/TFM/Dataset_preparados/dataset_kanji_parches/denoised/dataset_parches_denoised.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=1024, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=parches_denoised_1

## Análisis

El modelo denoised con imgsz=1024 obtiene los mejores resultados en precisión (0.938) y mAP50-95 (0.666) de todos los experimentos con parches. El recall (0.939) es ligeramente inferior al original 1024 (0.945) pero la diferencia es mínima.

Comparando original vs denoised con 1024, el denoised mejora en precisión y mAP50-95 mientras que el original tiene mejor recall ambos son configuraciones muy buenas y la elección depende de si se prioriza detectar más kanjis (recall → original) o tener menos falsos positivos (precisión → denoised).